#ifndef AKU_MODULES_ANDROID_CONFIG_H
#define AKU_MODULES_ANDROID_CONFIG_H

	#ifndef AKU_WITH_ANDROID
		#define AKU_WITH_ANDROID 1
	#endif

	#ifndef AKU_WITH_ANDROID_ADMOB
		#define AKU_WITH_ANDROID_ADMOB 1
	#endif

	#ifndef AKU_WITH_ANDROID_APPSFLYER
		#define AKU_WITH_ANDROID_APPSFLYER 1
	#endif

	#ifndef AKU_WITH_ANDROID_FACEBOOK
		#define AKU_WITH_ANDROID_FACEBOOK 1
	#endif

	#ifndef AKU_WITH_ANDROID_FIREBASE
		#define AKU_WITH_ANDROID_FIREBASE 1
	#endif
	
	#ifndef AKU_WITH_ANDROID_GOOGLE_BILLING
		#define AKU_WITH_ANDROID_GOOGLE_BILLING 1
	#endif

	#ifndef AKU_WITH_ANDROID_UNITY_ADS
		#define AKU_WITH_ANDROID_UNITY_ADS 1
	#endif
#endif