//
//  MessagesViewController.m
//  MessagesExtension
//
//  Created by Vavius on 22/08/16.
//  Copyright © 2016 Vavius. All rights reserved.
//

#import "MessagesViewController.h"
#import "MOAIMessagesView.h"

@interface MessagesViewController () {
	MOAIMessagesView* mMoaiView;
}
@end


@interface MessagesViewController ()

-( void ) onApplicationDidBecomeActive;
-( void ) onApplicationWillResignActive;

@end

@implementation MessagesViewController

-( void ) viewDidLoad {
	[ super viewDidLoad ];
	
	mMoaiView = [[ MOAIMessagesView alloc ] init ];
	
	mMoaiView.userInteractionEnabled = YES;
	mMoaiView.multipleTouchEnabled = YES;
	mMoaiView.alpha = 1.0f;
	mMoaiView.opaque = YES;
	
	[ mMoaiView moaiInit ];
	
	NSString* root = [[[ NSBundle mainBundle ] resourcePath ] stringByAppendingPathComponent:@"lua" ];
	[ mMoaiView setWorkingDirectory:root ];
	[ mMoaiView run:@"main.lua" ];
	
	self.view = mMoaiView;
	
	[[ NSNotificationCenter defaultCenter ] addObserver:self
											   selector:@selector(onApplicationDidBecomeActive)
												   name:UIApplicationDidBecomeActiveNotification
												 object:nil ];
	
	[[ NSNotificationCenter defaultCenter ] addObserver:self
											   selector:@selector(onApplicationWillResignActive)
												   name:UIApplicationWillResignActiveNotification
												 object:nil ];
}

-( void ) dealloc {
	[[ NSNotificationCenter defaultCenter] removeObserver:self ];
}

-( void ) didReceiveMemoryWarning {
	[ super didReceiveMemoryWarning ];
	// Dispose of any resources that can be recreated.
}

#pragma mark - Conversation Handling

-( void ) didBecomeActiveWithConversation: ( MSConversation* ) conversation {
	// Called when the extension is about to move from the inactive to active state.
	// This will happen when the extension is about to present UI.
	
	// Use this method to configure the extension and restore previously stored state.
	[ mMoaiView pause:NO ];
	[ MOAIMessagesView didBecomeActive:self withConversation:conversation ];
}

-( void ) willResignActiveWithConversation: ( MSConversation* ) conversation {
	// Called when the extension is about to move from the active to inactive state.
	// This will happen when the user dissmises the extension, changes to a different
	// conversation or quits Messages.
	
	// Use this method to release shared resources, save user data, invalidate timers,
	// and store enough state information to restore your extension to its current state
	// in case it is terminated later.
	[ mMoaiView pause:YES ];
	[ MOAIMessagesView willResignActive ];
}

-( void ) didReceiveMessage: ( MSMessage* ) message conversation: ( MSConversation* ) conversation {
	// Called when a message arrives that was generated by another instance of this
	// extension on a remote device.
	
	// Use this method to trigger UI updates in response to the message.
	[ MOAIMessagesView didReceiveMessage:message ];
}

-( void ) didSelectMessage:( MSMessage* ) message conversation:( MSConversation* )conversation {
	[ MOAIMessagesView didSelectMessage:message ];
}

-( void ) didStartSendingMessage: ( MSMessage* ) message conversation: ( MSConversation* ) conversation {
	// Called when the user taps the send button.
	[ MOAIMessagesView didStartSendingMessage:message ];
}

-( void ) didCancelSendingMessage: ( MSMessage* ) message conversation: ( MSConversation* ) conversation {
	// Called when the user deletes the message without sending it.
	
	// Use this to clean up state related to the deleted message.
	[ MOAIMessagesView didCancelSendingMessage:message ];
}

-( void ) willTransitionToPresentationStyle: ( MSMessagesAppPresentationStyle ) presentationStyle {
	// Called before the extension transitions to a new presentation style.
	
	// Use this method to prepare for the change in presentation style.
	[ MOAIMessagesView willTransitionToPresentationStyle:presentationStyle ];
}

-( void ) didTransitionToPresentationStyle: ( MSMessagesAppPresentationStyle ) presentationStyle {
	// Called after the extension transitions to a new presentation style.
	
	// Use this method to finalize any behaviors associated with the change in presentation style.
	[ MOAIMessagesView didTransitionToPresentationStyle:presentationStyle ];
}

-( void ) onApplicationDidBecomeActive {
	[ mMoaiView pause:NO ];
}

-( void ) onApplicationWillResignActive {
	[ mMoaiView pause:YES ];
}

-( void ) viewDidDisappear:( BOOL )animated {
	[ mMoaiView pause:YES ];
}

-( void ) viewWillAppear:( BOOL )animated {
	[ mMoaiView pause:NO ];
}


@end
